name: Build plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo $PWD
      - run: echo ${{ github.workspace }}

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: devopsfaith/krakend-plugin-builder:2.1.3
          options: -v ${{ github.workspace }}:/app -w /app
          run: |
            go build -buildmode=plugin -o cloud-run-service-account.so .

      - name: version
        run: echo "version=$(echo ${GITHUB_SHA} | head -c 7)" >> $GITHUB_ENV
        id: version

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.version }}
          files: ./cloud-run-service-account.so